### PR TITLE
"feat: adding button hover  effect #76"

### PR DESCRIPTION
**Pull request by Mubashir2611**
fixed the issue #76 
@Shinjan-saha check this out.

### CODE REVIEW

**Comment by Shinjan-saha** [comment]
Some latest Changes are not into your PR please check it

**Comment by Mubashir2611** [comment]
> Some latest Changes are not into your PR please check it

What changes ?

**Comment by Shinjan-saha** [comment]
> > Some latest Changes are not into your PR please check it
> 
> What changes? vercel deployment?

Upstream your branch with the main branch over here

**Comment by Mubashir2611** [comment]
> > > Some latest Changes are not into your PR please check it
> > 
> > 
> > What changes? vercel deployment?
> 
> Upstream your branch with the main branch over here

well, I am doing contribution on GitHub codespaces, so how to upstream my branch? please help.

**Comment by Shinjan-saha** [comment]
> > > > Some latest Changes are not into your PR please check it
> > > 
> > > 
> > > What changes? vercel deployment?
> > 
> > 
> > Upstream your branch with the main branch over here
> 
> well, I am doing contribution on GitHub codespaces, so how do upstream my branch? please help.

You van sync your fork with the main branch & then do the changes you are doing

**Comment by Mubashir2611** [comment]
> > > > > Some latest Changes are not into your PR please check it
> > > > 
> > > > 
> > > > What changes? vercel deployment?
> > > 
> > > 
> > > Upstream your branch with the main branch over here
> > 
> > 
> > well, I am doing contribution on GitHub codespaces, so how do upstream my branch? please help.
> 
> You van sync your fork with the main branch & then do the changes you are doing

done in #89

**Pull request closed without merging**
