### PR TITLE
Update The About Page

### PR DESCRIPTION
**Pull request by rko0211**
Screen Shot 2024-01-17 at 01 18 04

Please review my PR.

Resolve issue : #68

### CODE REVIEW

**Comment by Shinjan-saha** [comment]
Acha one think since you made the Top button, I didn't noticed it last time but can you please add the dark mode of the top button in the cart page also

**Comment by rko0211** [comment]
Ok i open an new issue for that. Kindly Merge this issue.

**Comment by Shinjan-saha** [comment]
No I will accept  this is this PR only no new issues for this

**Comment by rko0211** [comment]
OK i have changed, please check it now

**Pull request merged**
