### PR TITLE
#56 Done the changes in navcart and done some changes

### PR DESCRIPTION
**Pull request by Sneha123-zudo**
#56 Done the changes , please review my pull request and give suggestion if something need to be added.

### CODE REVIEW

**Comment by Shinjan-saha** [comment]
Screenshot_20240115-184304_Chrome
In about Try to write more about the Online Delivery system rather than the Canteen itself & also centre align the About Picture in Mobile version

**Comment by Sneha123-zudo** [comment]
Ok

**Comment by Shinjan-saha** [comment]
Please sync your fork with the latest Changes in main branch, some latest Changes are not visible

**Comment by Sneha123-zudo** [comment]
Please check

**Comment by Shinjan-saha** [comment]
Well you didn't updated the PR with the latest changes 
As asked i can still see that the Mobile version "Order Now" button is not proper it was fixed on previous PR but since it is not updated over here I can say that the your PR is still not yet updated with the latest Changes ease sync your Fork with the main branch of the Repo

**Pull request closed without merging**
