### PR TITLE
Cart neha

### PR DESCRIPTION
**Pull request by nsrs-78**

### CODE REVIEW

**Comment by Shinjan-saha** [comment]
Ok So here are few things:-
1) You removed the carousel section which should,nt happened
[
carousel-missing
](url)

2) Need Mobile Responsivness in Cart System  at Categories section 
mobile-responsivness-category

**Comment by nsrs-78** [comment]
Ok.. I'll be fixing it soon

**Comment by nsrs-78** [comment]
its done . check it out

**Comment by Shinjan-saha** [comment]
Awesome Work Loved It !!

**Pull request merged**
