### PR TITLE
Add Scroll back button in the website

### PR DESCRIPTION
**Pull request by rko0211**
You can see my work from here https://rko0211.github.io/Canteen-Website/

Kindly review my PR, Thank you

Resolve issue : #61

### CODE REVIEW

**Comment by Shinjan-saha** [comment]
Instead of just "Top" Written over button give it an arrow & if possible make the button Round Shape

**Comment by Shinjan-saha** [comment]
Also the button will have Diffrent Color for light & dark method, avoid red color & make the scroll smooth when it go to the home

**Comment by rko0211** [comment]
Kindly check it

**Comment by Shinjan-saha** [comment]
Check the previous conversation please & do the needed task

**Comment by rko0211** [comment]
> Check the previous conversation please & do the needed task

OK

**Comment by rko0211** [comment]
Please check it, now perfect every thing

**Comment by Shinjan-saha** [comment]
Good Work!!

**Comment by rko0211** [comment]
Thank you very much

**Pull request merged**
