### PR TITLE
Correct the possition of Light dark button

### PR DESCRIPTION
**Pull request by rko0211**
Kindly review my PR.

Fixes issue : #41

### CODE REVIEW

**Comment by Shinjan-saha** [comment]
switchlogoprob

In mobile version the logo  images is not when get  clicked

**Comment by rko0211** [comment]
It may be browser issue because in my browser there is no any kind of issue, kindly check it in your mobile phone .

In my mobile phone 
WhatsApp Image 2024-01-12 at 12 27 45 PM(1)

WhatsApp Image 2024-01-12 at 12 27 45 PM

**Comment by Shinjan-saha** [comment]
I don't think Logo image has something to do with browser when it was in menu it didn't have such problem, please see to this

**Comment by rko0211** [comment]
> I don't think Logo image has something to do with browser when it was in menu it didn't have such problem, please see to this

 i have seen it kindly check it by your mobile devices then tell me..

**Comment by rko0211** [comment]
> I don't think Logo image has something to do with browser when it was in menu it didn't have such problem, please see to this

One extra reason that is your browser is not connected with internet.

**Comment by Shinjan-saha** [comment]
Sync your PR with the Latest Changes in Main branch

**Pull request closed without merging**
